services:
  - type: web
    name: qr-based-file-transfer
    env: node
    buildCommand: |
      # Install backend dependencies
      npm install
      
      # Install and build frontend
      cd client
      npm install
      CI=false npm run build
      
      # Create and populate public directory
      cd ..
      rm -rf public
      mkdir -p public
      
      # Copy frontend build files
      cp -r client/build/* public/
      
      # Ensure qr-upload.html exists
      if [ ! -f "public/qr-upload.html" ]; then
        echo "Creating qr-upload.html..."
        cp public/index.html public/qr-upload.html
      fi
      
      # Verify critical files
      echo "Verifying build output..."
      ls -la public/
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://qr-based-file-transfer.onrender.com
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false 