services:
  - type: web
    name: qr-file-transfer-backend
    env: node
    buildCommand: |
      npm install
      cd client
      npm install
      npm run build
      cd ..
      mkdir -p public
      cp -r client/build/* public/
      cp public/qr-upload.html public/
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false 