services:
  - type: web
    name: qr-file-transfer-backend
    env: node
    buildCommand: |
      # Install backend dependencies
      npm install
      
      # Install and build frontend
      cd client
      npm install
      CI=false npm run build
      
      # Create and populate public directory
      cd ..
      rm -rf public
      mkdir -p public
      
      # Copy frontend build files
      cp -r client/build/* public/
      
      # Ensure qr-upload.html exists
      if [ ! -f "public/qr-upload.html" ]; then
        echo "Creating qr-upload.html..."
        echo "<!DOCTYPE html><html><head><title>QR Upload</title></head><body><h1>QR Upload Page</h1></body></html>" > public/qr-upload.html
      fi
      
      # Verify critical files
      echo "Verifying build output..."
      ls -la public/
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false 